# OpenAL Soft settings for the console (read through ALSOFT_CONF, port.ini). The console's ALSA device takes only
# 16-bit samples: OpenAL Soft's default (float) is refused with "snd_pcm_hw_params failed: Invalid argument" and the
# engine then runs without sound. Licence: GPL-3.0-only, like the rest of this package.
[general]
sample-type = int16
frequency = 44100
